"""usuarios con auth

Revision ID: be72d60636c0
Revises: 65f8b505e3e7
Create Date: 2026-09-28 12:12:09.779383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be72d60636c0'
down_revision: Union[str, Sequence[str], None] = '65f8b505e3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_column('productos', 'cuotas_cantidad')
    op.drop_column('productos', 'stock')
    op.drop_column('productos', 'cuotas_valor')
    op.drop_column('productos', 'garantia_meses')
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(), nullable=True))
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'hashed_password')
    op.add_column('productos', sa.Column('garantia_meses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('cuotas_valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('cuotas_cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('pedidos_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pedidos_pkey'))
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('items_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('items_pedido_pedido_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('items_pedido_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pedido_pkey'))
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    # ### end Alembic commands ###
